Личный проект: прикрой меня тестом
htmlacademy-nodejs/521287-typoteka-3 pull request #14
Opened 2020-12-13 16:30 UTC by ilyasidorchik

2020-12-19 12:46 UTC, muturgan commented on src/service/api/search/search.js
> +      return res.status(HttpCode.BAD_REQUEST).json([]);
отличный подход

2020-12-26 12:24 UTC, Krabaton requested changes
Попробовать взять данные из моков. Убрать магические числа и значения.

2020-12-26 12:24 UTC, Krabaton commented on src/service/api/articles/articles.e2e.test.js
> +    expect(response.body[0].id).toBe(`Qzw3gs`);
Что это Qzw3gs? Плохо так делать. Я так понимаю есть мок данные, которые  мы подкидываем для роутов. Значит надо сравнивать, что роуты возвращают те же данные что мы им скормили, и  вытягивать из мока, чтобы если изменять то в одном месте.

2020-12-26 12:24 UTC, Krabaton commented on src/service/api/articles/articles.e2e.test.js
> +    response = await request(app).get(`/articles/ghJIDB`);
Опять запрос со специфичным id

2020-12-26 12:24 UTC, Krabaton commented on src/service/api/articles/articles.e2e.test.js
> +      response = await request(app).post(`/articles`).send(newArticle);
Вот тут хорошо, что скормили с тем и сравниваем.

2020-12-26 12:24 UTC, Krabaton commented on src/service/api/articles/articles.e2e.test.js
> +      expect(articleResponse.body.length).toBe(6);
Опять магическое число 6. Вытащит из моков данные узнать длину и сравнивать с тем, что вернет роут.

2020-12-26 12:24 UTC, Krabaton commented on src/service/api/articles/articles.e2e.test.js
> +  describe(`−`, () => {
Название обещающее) -

2020-12-26 12:24 UTC, Krabaton commented on src/service/api/articles/articles.e2e.test.js
> +      response = await request(app).put(`/articles/Adjh2S`).send(changedArticle);
Опять же изменение значения id в моке уронит нам тест.

2020-12-26 12:24 UTC, Krabaton commented on src/service/api/articles/articles.e2e.test.js
> +  describe(`−`, () => {
Да почему минус то? Вместо + и - лучше поставить осмысленные названия
Checking successful requests
Checking for errors

2020-12-26 12:24 UTC, Krabaton commented on src/service/api/articles/utils.js
> +  const cloneData = JSON.parse(JSON.stringify(mockData));
так, а зачем и в чем смысл?

2020-12-26 12:24 UTC, Krabaton commented on src/service/app.js
> +  logger.error(`An error's occured on processing request: ${err.message}`);
Надо серверу, что-то фронту сообщить все-таки. Он же будет просто ждать ответ напрасно. Типа хоть - все плохо и сервер ушел на покой) 503 братья

2020-12-26 17:51 UTC, ilyasidorchik commented on src/service/app.js
> +  logger.error(`An error's occured on processing request: ${err.message}`);
/fixed

2020-12-26 17:55 UTC, ilyasidorchik commented on src/service/api/articles/articles.e2e.test.js
> +  describe(`−`, () => {
Понимаю минус такого подхода, но, как мне кажется, есть более важный плюс. Когда много тестов, так легче отделяются положительные и негативные сценарии.

2020-12-26 17:55 UTC, ilyasidorchik commented on src/service/api/articles/utils.js
> +  const cloneData = JSON.parse(JSON.stringify(mockData));
Мутирующие операции, произведённые в одном тесте, могут повлиять на другой тест, если они используют один и тот же источник данных. Как сделать, чтобы этого не происходило? Один из вариантов — создавать API заново перед каждым тестом.

_Учебник Хтмл-академии. [Прохождение домашки по тестам](https://up.htmlacademy.ru/nodejs/3/book/4.13)_

2020-12-26 17:55 UTC, ilyasidorchik commented on src/service/api/articles/articles.e2e.test.js
> +      response = await request(app).put(`/articles/Adjh2S`).send(changedArticle);
/fixed

2020-12-26 17:55 UTC, ilyasidorchik commented on src/service/api/articles/articles.e2e.test.js
> +      expect(articleResponse.body.length).toBe(6);
/fixed

2020-12-26 17:55 UTC, ilyasidorchik commented on src/service/api/articles/articles.e2e.test.js
> +    response = await request(app).get(`/articles/ghJIDB`);
/fixed

2020-12-26 17:55 UTC, ilyasidorchik commented on src/service/api/articles/articles.e2e.test.js
> +    expect(response.body[0].id).toBe(`Qzw3gs`);
/fixed

2020-12-27 15:58 UTC, Krabaton commented on src/service/api/articles/utils.js
> +  const cloneData = JSON.parse(JSON.stringify(mockData));
Нет вопрос, про `JSON.parse(JSON.stringify(mockData))` К чему мы данные так преобразуем? Из объекта опять в объект.

2020-12-27 16:00 UTC, Krabaton commented on src/service/api/articles/articles.e2e.test.js
> +  describe(`−`, () => {
Ну в целом да, тут уже вкусовщина. Мне вместо плюсов проще сообщения. Согласен

2020-12-27 16:10 UTC, merged